# Generated by Django 5.2.5 on 2026-05-12 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_member', models.CharField(editable=False, max_length=20, unique=True)),
                ('tanggal_bergabung', models.DateField(auto_now_add=True)),
                ('salutation', models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=10)),
                ('nama_tengah', models.CharField(blank=True, max_length=100, null=True)),
                ('kewarganegaraan', models.CharField(default='Indonesia', max_length=100)),
                ('country_code', models.CharField(default='+62', max_length=5)),
                ('nomor_hp', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
