# Generated by Django 5.2.5 on 2026-04-29 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('tipe', models.CharField(choices=[('airline', 'Airline'), ('partner', 'Partner')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hadiah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(editable=False, max_length=10, unique=True)),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('miles', models.IntegerField()),
                ('valid_start', models.DateField()),
                ('valid_end', models.DateField()),
                ('penyedia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rewards.penyedia')),
            ],
        ),
    ]
