# Generated by Django 5.2.5 on 2026-04-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mitra',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_kerja_sama', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='penyedia',
            old_name='nama',
            new_name='nama_penyedia',
        ),
        migrations.AlterField(
            model_name='penyedia',
            name='tipe',
            field=models.CharField(choices=[('airline', 'Airline'), ('partner', 'Partner')], default='partner', max_length=20),
        ),
        migrations.AddField(
            model_name='penyedia',
            name='mitra',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='rewards.mitra'),
            preserve_default=False,
        ),
    ]
