# Generated by Django 5.2.5 on 2026-05-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_mitra_rename_nama_penyedia_nama_penyedia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyedia',
            name='mitra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penyedia', to='rewards.mitra'),
        ),
    ]
