# Generated by Django 5.2.5 on 2026-05-15 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_penyedia_mitra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penyedia',
            name='mitra',
        ),
        migrations.DeleteModel(
            name='Hadiah',
        ),
        migrations.DeleteModel(
            name='Mitra',
        ),
        migrations.DeleteModel(
            name='Penyedia',
        ),
    ]
